# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='contents.Page', verbose_name='Página'),
            preserve_default=False,
        ),
    ]
