# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_content_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['id'], 'verbose_name': 'Conteúdo', 'verbose_name_plural': 'Conteúdos'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['id'], 'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
    ]
