# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170518_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='vimeo',
            field=models.TextField(blank=True, null=True, verbose_name='Embed vimeo'),
        ),
    ]
