# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170518_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectPhotos',
            new_name='ProjectPhoto',
        ),
    ]
