# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170518_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphoto',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projects.Project'),
        ),
    ]
