# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20170518_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coverphoto',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='projectcoverphotos/%Y/%m/%d/', verbose_name='Foto de capa'),
        ),
    ]
