# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='Solutions',
            new_name='Solution',
        ),
    ]
