# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170622_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='home',
            field=models.BooleanField(default=False, verbose_name='Colocar na home'),
        ),
    ]
