# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_solution_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'verbose_name': 'Solução', 'verbose_name_plural': 'Soluções'},
        ),
    ]
