# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20170823_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link Vimeo'),
        ),
    ]
