# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Setor')),
                ('testimonial', models.TextField(verbose_name='Testimonial')),
                ('photo', models.ImageField(max_length=255, upload_to='clientphotos/%Y/%m/%d/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
