# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-19 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiovisual', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='servicesphotos/%Y/%m/%d/', verbose_name='Foto'),
        ),
    ]
