# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-29 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link Vimeo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='solutionsphotos/%Y/%m/%d/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.RemoveField(
            model_name='portfolioclient',
            name='user',
        ),
        migrations.DeleteModel(
            name='PortfolioClient',
        ),
    ]
